plugins {
    kotlin("multiplatform")
}

repositories {
    google()
    mavenCentral()
}

/**
 * The "Web application" OAuth client of the published app — the one the popup flow and the extension's
 * `launchWebAuthFlow` fallback identify themselves to Google as, and the one the server checks the token's
 * `aud` against. Public by nature, like the extension client id in `manifest.json`: it names the
 * application, and everything that makes the flow safe (the registered redirect URIs, the signature check
 * on the server) is elsewhere. A fork overrides it with STRAMUS_GOOGLE_CLIENT_ID.
 */
val PUBLISHED_GOOGLE_CLIENT_ID = "18928481720-2qrnmhlm21jvi6f6qlgnd2lqcau2joi6.apps.googleusercontent.com"

// The sync server has no fixed address the source could name (a developer's is on localhost, and the
// deployed one is whoever's VPS it ends up on) — so it comes from the environment at build time instead,
// the same way CI already keeps other secrets out of the source. Locally, and in any build that does not
// set it, this is blank and `serverBaseUrl()` falls back to localhost, exactly as before.
//
// The Google client id goes the same way, for a different reason. It is not a secret — it is a public
// identifier tied 1:1 to this application, checked into `manifest.json` already for the other OAuth client —
// but until now it lived *only* in `localStorage`, set by hand, per browser profile and per origin. That
// made a browser nobody had prepared a browser where the sign-in button did nothing at all, which is what
// Edge was. So it is baked in, with `localStorage` still overriding it for a fork or a test build.
val generateBuildDefaults = tasks.register("generateBuildDefaults") {
    val serverUrl = providers.environmentVariable("STRAMUS_SERVER_URL").getOrElse("")
    // Blank counts as "not set": an unset GitHub Actions variable arrives as an empty string, and taking
    // that literally would ship a build with no client id and no Google button at all.
    val googleClientId = providers.environmentVariable("STRAMUS_GOOGLE_CLIENT_ID").orNull
        ?.takeIf { it.isNotBlank() }
        ?: PUBLISHED_GOOGLE_CLIENT_ID
    val outputDir = layout.buildDirectory.dir("generated/buildDefaults")
    inputs.property("serverUrl", serverUrl)
    inputs.property("googleClientId", googleClientId)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("BuildDefaults.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package stramus.ui

            // Generated by :ui-shared:generateBuildDefaults from the STRAMUS_SERVER_URL and
            // STRAMUS_GOOGLE_CLIENT_ID environment variables — see build.gradle.kts. Do not edit by hand.
            internal const val DEFAULT_SERVER_URL: String = "$serverUrl"
            internal const val DEFAULT_GOOGLE_CLIENT_ID: String = "$googleClientId"

            """.trimIndent(),
        )
    }
}

// Shared React UI for both entry points (webapp + extension). Exposes the kotlin-wrappers React
// stack as `api` so the thin per-app `main()` (createRoot) compiles without re-declaring them.
kotlin {
    js {
        browser()
    }

    sourceSets {
        val jsMain by getting {
            kotlin.srcDir(generateBuildDefaults)
            dependencies {
                api(project(":core"))

                api(project.dependencies.enforcedPlatform("org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:2026.7.1"))
                api("org.jetbrains.kotlin-wrappers:kotlin-react")
                api("org.jetbrains.kotlin-wrappers:kotlin-react-dom")
                api("org.jetbrains.kotlin-wrappers:kotlin-browser")

                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            }
        }
    }
}
