plugins {
    kotlin("multiplatform")
}

repositories {
    google()
    mavenCentral()
}

// The sync server has no fixed address the source could name (a developer's is on localhost, and the
// deployed one is whoever's VPS it ends up on) — so it comes from the environment at build time instead,
// the same way CI already keeps other secrets out of the source. Locally, and in any build that does not
// set it, this is blank and `serverBaseUrl()` falls back to localhost, exactly as before.
val generateDefaultServerUrl = tasks.register("generateDefaultServerUrl") {
    val serverUrl = providers.environmentVariable("STRAMUS_SERVER_URL").getOrElse("")
    val outputDir = layout.buildDirectory.dir("generated/defaultServerUrl")
    inputs.property("serverUrl", serverUrl)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("DefaultServerUrl.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package stramus.ui

            // Generated by :ui-shared:generateDefaultServerUrl from the STRAMUS_SERVER_URL environment
            // variable — see build.gradle.kts. Do not edit by hand.
            internal const val DEFAULT_SERVER_URL: String = "$serverUrl"

            """.trimIndent(),
        )
    }
}

// Shared React UI for both entry points (webapp + extension). Exposes the kotlin-wrappers React
// stack as `api` so the thin per-app `main()` (createRoot) compiles without re-declaring them.
kotlin {
    js {
        browser()
    }

    sourceSets {
        val jsMain by getting {
            kotlin.srcDir(generateDefaultServerUrl)
            dependencies {
                api(project(":core"))

                api(project.dependencies.enforcedPlatform("org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom:2026.7.1"))
                api("org.jetbrains.kotlin-wrappers:kotlin-react")
                api("org.jetbrains.kotlin-wrappers:kotlin-react-dom")
                api("org.jetbrains.kotlin-wrappers:kotlin-browser")

                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
            }
        }
    }
}
